version: '3.4'
    
services:
  db:
    image: postgres
    restart: always
    container_name: db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
    environment:
      POSTGRES_PASSWORD: password

  weather-informer:
    build:
      context: ./
      dockerfile: Dockerfile
    image: weather-informer
    ports:
      - "3000:3000"
    
    restart: always
    container_name: weather-informer
    depends_on:
      - db
    links:
      - db 
    environment:
      RAILS_ENV: 'production'
      RACK_ENV: 'production'
      RAILS_SERVE_STATIC_FILES: 'true'
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME:
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
      SECRET_KEY_BASE:

      WEATHER_SERVICE_CITY_URL:
      WEATHER_SERVICE_WEATHER_URL:
      WEATHER_SERVICE_API_KEY:

      RAILS_LOG_TO_STDOUT: 'true'
      

